# Einfaches Beispiel zum lösen von linearen Gleichungssystemen in Python

## Rein numerisch via numpy

In [1]:
import numpy as np

In [2]:
# Durch Netzwerk gegeben, wobei G bereits verrechnet wurde:
YK = np.array([[3,-1,-1/2,-1/2],[-1,3,-1,-1/2],[-1/2,-1,3,-1],[-1/2,-1/2,-1,3]])
print("YK:\n" + str(YK))

iq = np.array([[10+3j],[0],[0],[5]])
print("uq:\n" + str(iq))

YK:
[[ 3.  -1.  -0.5 -0.5]
 [-1.   3.  -1.  -0.5]
 [-0.5 -1.   3.  -1. ]
 [-0.5 -0.5 -1.   3. ]]
uq:
[[10.+3.j]
 [ 0.+0.j]
 [ 0.+0.j]
 [ 5.+0.j]]


In [3]:
# Bestimmung der inversen Matrix
inv_YK = np.linalg.inv(YK)
print("inv_YK:\n" + str(inv_YK))

inv_YK:
[[0.50909091 0.29090909 0.25454545 0.21818182]
 [0.29090909 0.58181818 0.32727273 0.25454545]
 [0.25454545 0.32727273 0.58181818 0.29090909]
 [0.21818182 0.25454545 0.29090909 0.50909091]]


In [4]:
# Berechnung der gesuchten Größen
phi = inv_YK.dot(iq)
print("phi:\n" + str(phi))

phi:
[[6.18181818+1.52727273j]
 [4.18181818+0.87272727j]
 [4.        +0.76363636j]
 [4.72727273+0.65454545j]]


## Symbolisch via sympy

In [5]:
import sympy as sp

In [6]:
# Symbol definition für alle variablen Größen
p1, p2, p3, p4 = sp.symbols('p1:5')
uq1, uq2 = sp.symbols('uq1:3')
G = sp.symbols('G')

In [7]:
# Durch Netzwerk gegeben:
# [Der Zusatz "_s" dient nur der Unterscheidung zur vorherigen Methode.]
YK_s = sp.Matrix( [[3,-1,-1/2,-1/2], [-1,3,-1,-1/2], [-1/2,-1,3,-1], [-1/2,-1/2,-1,3]] ) * G
print("YK:\n" + sp.pretty(YK_s, use_unicode=True))

iq_s = sp.Matrix( [[uq1],[0],[0],[uq2]] ) * G
print("siq:\n" + sp.pretty(iq_s, use_unicode=True))

YK:
⎡ 3⋅G      -G    -0.5⋅G  -0.5⋅G⎤
⎢                              ⎥
⎢  -G     3⋅G      -G    -0.5⋅G⎥
⎢                              ⎥
⎢-0.5⋅G    -G     3⋅G      -G  ⎥
⎢                              ⎥
⎣-0.5⋅G  -0.5⋅G    -G     3⋅G  ⎦
siq:
⎡G⋅uq₁⎤
⎢     ⎥
⎢  0  ⎥
⎢     ⎥
⎢  0  ⎥
⎢     ⎥
⎣G⋅uq₂⎦


In [8]:
# Bestimmung der inversen Matrix
inv_YK_s = YK_s.inv()
print("inv_YK:\n" + sp.pretty(inv_YK_s))

inv_YK:
⎡0.509090909090909  0.290909090909091  0.254545454545455  0.218181818181818⎤
⎢─────────────────  ─────────────────  ─────────────────  ─────────────────⎥
⎢        G                  G                  G                  G        ⎥
⎢                                                                          ⎥
⎢0.290909090909091  0.581818181818182  0.327272727272727  0.254545454545455⎥
⎢─────────────────  ─────────────────  ─────────────────  ─────────────────⎥
⎢        G                  G                  G                  G        ⎥
⎢                                                                          ⎥
⎢0.254545454545455  0.327272727272727  0.581818181818182  0.290909090909091⎥
⎢─────────────────  ─────────────────  ─────────────────  ─────────────────⎥
⎢        G                  G                  G                  G        ⎥
⎢                                                                          ⎥
⎢0.218181818181818  0.254545454545455  0.290909090909091  0.50909090

In [9]:
# Berechnung der gesuchten Größen
phi_s = inv_YK_s * iq_s
print("phi:\n" + sp.pretty(phi_s))

phi:
⎡0.509090909090909⋅uq₁ + 0.218181818181818⋅uq₂⎤
⎢                                             ⎥
⎢0.290909090909091⋅uq₁ + 0.254545454545455⋅uq₂⎥
⎢                                             ⎥
⎢0.254545454545455⋅uq₁ + 0.290909090909091⋅uq₂⎥
⎢                                             ⎥
⎣0.218181818181818⋅uq₁ + 0.509090909090909⋅uq₂⎦


In [10]:
# Alternativ beide vorherigen Schritte in einem:
sol = sp.linsolve((YK_s, iq_s), [p1, p2, p3, p4])
print("phi:\n" + sp.pretty(sol))

phi:
{(0.509090909090909⋅uq₁ + 0.218181818181818⋅uq₂, 0.290909090909091⋅uq₁ + 0.254
545454545455⋅uq₂, 0.254545454545455⋅uq₁ + 0.290909090909091⋅uq₂, 0.21818181818
1818⋅uq₁ + 0.509090909090909⋅uq₂)}


In [11]:
# Numerische Werte erhält man dann durch Substitution
phi_s_num = phi_s.subs([(uq1, 10+3j), (uq2, 5)])
print("phi nach substitution:\n" + sp.pretty(phi_s_num, ))

sol_num = sol.subs([(uq1, 10+3j), (uq2, 5)])
print("sol nach substitution:\n" + sp.pretty(sol_num))

phi nach substitution:
⎡6.18181818181818 + 1.52727272727273⋅ⅈ ⎤
⎢                                      ⎥
⎢4.18181818181818 + 0.872727272727273⋅ⅈ⎥
⎢                                      ⎥
⎢      4.0 + 0.763636363636364⋅ⅈ       ⎥
⎢                                      ⎥
⎣4.72727272727273 + 0.654545454545455⋅ⅈ⎦
sol nach substitution:
{(6.18181818181818 + 1.52727272727273⋅ⅈ, 4.18181818181818 + 0.872727272727273⋅
ⅈ, 4.0 + 0.763636363636364⋅ⅈ, 4.72727272727273 + 0.654545454545455⋅ⅈ)}
